name: Run Daily Sales ETL

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  run-etl-job:
    runs-on: ubuntu-latest 

    steps:
    - name: 1. Check out code
      uses: actions/checkout@v4

    - name: 2. Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.4'

    - name: 3. Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: 4. Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: 5. Run the ETL script
      run: |
        python src/extract_and_load_to_s3.py